# Generated by Django 3.0.5 on 2020-06-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('list_reponse', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25, unique=True)),
                ('prenom', models.CharField(max_length=25, unique=True)),
                ('num', models.CharField(default='', max_length=8, unique=True)),
                ('role', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listReponse', models.CharField(max_length=100, null=True)),
                ('FK_Question', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question')),
                ('FK_Utilisateur', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('listRepondant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_liste_utilisateur', to='menu_questionnaire.Utilisateur')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_create_utilisateur', to='menu_questionnaire.Utilisateur')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_first_question', to='menu_questionnaire.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='FK_Questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_questionnaire_associe', to='menu_questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu_questionnaire.Question'),
        ),
    ]
