# Generated by Django 3.0.5 on 2020-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='libelle',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
