# Generated by Django 3.0.5 on 2020-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(default='etudiant', max_length=25, unique=True),
        ),
    ]
