# Generated by Django 3.0.5 on 2020-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bonne_reponse',
            field=models.ManyToManyField(blank=True, related_name='question_liste_de_bonne_reponse', to='menu_questionnaire.Reponse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='question',
            name='libelle',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='list_reponse',
        ),
        migrations.AddField(
            model_name='question',
            name='list_reponse',
            field=models.ManyToManyField(blank=True, related_name='question_liste_de_reponse', to='menu_questionnaire.Reponse'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.ManyToManyField(blank=True, to='menu_questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=25),
        ),
    ]
