# Generated by Django 3.0.5 on 2020-04-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0002_auto_20200425_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=25, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='Questionnaire',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Reponse',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='dateCreation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReponse', models.DateTimeField(null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_questionnaire.Question')),
                ('reponse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_questionnaire.Reponse')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_questionnaire.Etudiant'),
        ),
    ]
