# Generated by Django 3.0.5 on 2020-06-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0002_auto_20200604_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='FK_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='FK_Utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(default='etudiant', max_length=25),
        ),
    ]
