# Generated by Django 3.0.5 on 2020-04-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0003_auto_20200426_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question'),
        ),
    ]
