# Generated by Django 3.0.5 on 2020-04-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0004_auto_20200426_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questionnaire',
            new_name='listeQ',
        ),
    ]
