# Generated by Django 3.0.5 on 2020-04-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0006_auto_20200428_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='dateCreation',
        ),
    ]
