# Generated by Django 3.0.5 on 2020-04-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0007_remove_questionnaire_datecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='questionreponse',
            name='dateReponse',
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Etudiant'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='questionreponse',
            name='reponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Reponse'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question'),
        ),
    ]
