# Generated by Django 3.0.5 on 2020-04-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0008_auto_20200429_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='reponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Reponse'),
        ),
    ]
