# Generated by Django 3.0.5 on 2020-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0009_auto_20200429_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='listQuestion',
            field=models.ManyToManyField(to='menu_questionnaire.Question'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='reponse',
        ),
        migrations.AddField(
            model_name='question',
            name='reponse',
            field=models.ManyToManyField(to='menu_questionnaire.Reponse'),
        ),
    ]
