# Generated by Django 3.0.5 on 2020-05-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0010_auto_20200430_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionReponse',
        ),
    ]
