# Generated by Django 3.0.5 on 2020-05-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0011_delete_questionreponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Etudiant')),
                ('FK_Question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Question')),
                ('FK_Questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_questionnaire.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='reponseEtu',
            field=models.ManyToManyField(through='menu_questionnaire.QuestionnaireQuestion', to='menu_questionnaire.Questionnaire'),
        ),
    ]
