# Generated by Django 3.0.5 on 2020-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_questionnaire', '0012_auto_20200504_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='reponseEtu',
            new_name='TableauEtu',
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='ReponseEtu',
            field=models.TextField(null=True),
        ),
    ]
